<template>
  <div class="min-h-screen bg-gray-100">
    <header class="bg-green-600 text-white p-5 shadow-lg">
      <h1 class="text-3xl font-bold text-center">Team Management</h1>
    </header>

    <main class="container mx-auto p-5">

      <!-- Create Team Section -->
      <section class="mb-10">
        <h2 class="text-xl font-bold mb-4">Create a Team</h2>
        <div class="bg-white shadow-md p-6 rounded-lg">
          <input v-model="newTeam.name" type="text" placeholder="Team Name" class="input-field" />
          <button @click="createTeam" class="btn-primary">Create Team</button>
          <p v-if="errorMessage" class="text-red-500">{{ errorMessage }}</p>
          <p v-if="successMessage" class="text-green-500">{{ successMessage }}</p>
        </div>
      </section>

      <!-- Team List Section -->
      <section>
        <h2 class="text-xl font-bold mb-4">Team List</h2>
        <div class="bg-white shadow-md p-6 rounded-lg">
          <table class="table-auto w-full text-left">
            <thead>
              <tr class="bg-green-600 text-white">
                <th class="p-3">ID</th>
                <th class="p-3">Name</th>
                <th class="p-3">Points</th>
                <th class="p-3">Creator ID</th>
                <th class="p-3">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="team in teams" :key="team.id" class="border-t">
                <td class="p-3">{{ team.id }}</td>
                <td class="p-3">{{ team.name }}</td>
                <td class="p-3">{{ team.points }}</td>
                <td class="p-3">{{ team.creatorId }}</td>
                <td class="p-3">
                  <button @click="deleteTeam(team.id)" class="btn-danger">Delete</button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>
    </main>
  </div>
</template>

<script>
import apiClient from "@/axios";

export default {
  data() {
    return {
      teams: [],
      newTeam: {
        name: "",
        points: 0,
        creatorId: null,
        homeMatches: [],
        awayMatches: []
      },
      errorMessage: "",
      successMessage: "",
    };
  },
  computed: {
    user() {
      return this.$store.state.user;
    },
    token() {
      return this.$store.state.user.token;
    }
  },
  methods: {
    async fetchTeams() {
      try {
        console.log("Fetching teams with token:", this.token); // Debugging log
        const response = await apiClient.post("/Team", { token: this.token }, {
          headers: {
            Authorization: `Bearer ${this.token}`,
            'Content-Type': 'application/json'
          },
        });
        this.teams = response.data;
      } catch (error) {
        console.error("Error fetching teams", error);
      }
    },
    async createTeam() {
      if (!this.newTeam.name.trim()) {
        this.errorMessage = "Team name is required.";
        return;
      }

      console.log("Creating team with token:", this.token); // Debugging log

      try {
        const response = await apiClient.post("/Team", {
          id: 0, // Assuming the ID is auto-generated by the server
          name: this.newTeam.name,
          points: this.newTeam.points,
          creatorId: this.user.id,
          homeMatches: this.newTeam.homeMatches,
          awayMatches: this.newTeam.awayMatches,
          token: this.token // Include the token in the request body
        }, {
          headers: {
            Authorization: `Bearer ${this.token}`,
            'Content-Type': 'application/json'
          },
        });
        console.log("Team creation response:", response); // Debugging log
        this.newTeam.name = "";
        this.newTeam.points = 0;
        this.newTeam.homeMatches = [];
        this.newTeam.awayMatches = [];
        this.successMessage = "Team created successfully!";
        this.errorMessage = "";
        this.fetchTeams();
      } catch (error) {
        console.error("Error creating team:", error.response?.data || error.message);
        this.errorMessage = error.response?.data?.message || "Failed to create team.";
        this.successMessage = "";
      }
    },
    async deleteTeam(teamId) {
      try {
        console.log("Deleting team with token:", this.token); // Debugging log
        await apiClient.delete(`/Team/${teamId}`, {
          headers: {
            Authorization: `Bearer ${this.token}`,
          },
        });
        this.fetchTeams();
      } catch (error) {
        console.error("Error deleting team", error);
      }
    },
  },
  created() {
    this.$store.dispatch('checkUser');
    this.fetchTeams();
  },
};
</script>

<style>
.input-field {
  width: 100%;
  border: 1px solid #ddd;
  padding: 10px;
  margin-bottom: 10px;
  border-radius: 5px;
}
.btn-primary {
  background-color: #28a745;
  color: white;
  padding: 10px 15px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}
.btn-primary:disabled {
  background-color: #ccc;
  cursor: not-allowed;
}
.btn-danger {
  background-color: #dc3545;
  color: white;
  padding: 5px 10px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}
table {
  width: 100%;
  border-collapse: collapse;
}
th,
td {
  padding: 10px;
  border: 1px solid #ddd;
}
th {
  background-color: #28a745;
  color: white;
}
</style>